// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaArtigos.API.Data;

#nullable disable

namespace SistemaArtigos.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261007205720_AdicionaTabelaRascunhos")]
    partial class AdicionaTabelaRascunhos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SistemaArtigos.API.Models.Artigo", b =>
                {
                    b.Property<int>("IdArtigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_artigo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdArtigo"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("varchar(10000)")
                        .HasColumnName("conteudo");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("NivelArtigo")
                        .IsRequired()
                        .HasColumnType("enum('iniciante','intermediario','avancado','comunidade')")
                        .HasColumnName("nivel_artigo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('publicado','em_analise')")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("titulo");

                    b.HasKey("IdArtigo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("artigos");
                });

            modelBuilder.Entity("SistemaArtigos.API.Models.Avaliacao", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IdArtigo")
                        .HasColumnType("int")
                        .HasColumnName("id_artigo");

                    b.Property<DateTime>("DataDeAvaliacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_avaliacao");

                    b.Property<int>("Nota")
                        .HasColumnType("int")
                        .HasColumnName("nota");

                    b.HasKey("IdUsuario", "IdArtigo");

                    b.HasIndex("IdArtigo");

                    b.ToTable("avaliacoes");
                });

            modelBuilder.Entity("SistemaArtigos.API.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(10000)
                        .HasColumnType("varchar(10000)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("IdCategoria");

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("SistemaArtigos.API.Models.CategoriaDArtigo", b =>
                {
                    b.Property<int>("IdArtigo")
                        .HasColumnType("int")
                        .HasColumnName("id_artigo");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.HasKey("IdArtigo", "IdCategoria");

                    b.HasIndex("IdCategoria");

                    b.ToTable("categorias_d_artigos");
                });

            modelBuilder.Entity("SistemaArtigos.API.Models.Comentario", b =>
                {
                    b.Property<int>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_comentario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdComentario"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("DataComentario")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_comentario");

                    b.Property<int>("IdArtigo")
                        .HasColumnType("int")
                        .HasColumnName("id_artigo");

                    b.Property<int?>("IdComentarioPai")
                        .HasColumnType("int")
                        .HasColumnName("id_comentario_pai");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdComentario");

                    b.HasIndex("IdArtigo");

                    b.HasIndex("IdComentarioPai");

                    b.HasIndex("IdUsuario");

                    b.ToTable("comentarios");
                });

            modelBuilder.Entity("SistemaArtigos.API.Models.Favorito", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IdArtigo")
                        .HasColumnType("int")
                        .HasColumnName("id_artigo");

                    b.HasKey("IdUsuario", "IdArtigo");

                    b.HasIndex("IdArtigo");

                    b.ToTable("favoritos");
                });

            modelBuilder.Entity("SistemaArtigos.API.Models.RascunhoDArtigo", b =>
                {
                    b.Property<int>("IdRascunho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rascunho");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRascunho"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("titulo");

                    b.HasKey("IdRascunho");

                    b.HasIndex("IdUsuario");

                    b.ToTable("rascunhos_d_artigos");
                });

            modelBuilder.Entity("SistemaArtigos.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("NivelDeAcesso")
                        .HasColumnType("enum('admin','moderador','leitor')")
                        .HasColumnName("nivel_d_acesso");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<int?>("ScoreReputacao")
                        .HasColumnType("int")
                        .HasColumnName("score_reputacao");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("SistemaArtigos.API.Models.Artigo", b =>
                {
                    b.HasOne("SistemaArtigos.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaArtigos.API.Models.Avaliacao", b =>
                {
                    b.HasOne("SistemaArtigos.API.Models.Artigo", "Artigo")
                        .WithMany()
                        .HasForeignKey("IdArtigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaArtigos.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artigo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaArtigos.API.Models.CategoriaDArtigo", b =>
                {
                    b.HasOne("SistemaArtigos.API.Models.Artigo", "Artigo")
                        .WithMany()
                        .HasForeignKey("IdArtigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaArtigos.API.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artigo");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SistemaArtigos.API.Models.Comentario", b =>
                {
                    b.HasOne("SistemaArtigos.API.Models.Artigo", "Artigo")
                        .WithMany()
                        .HasForeignKey("IdArtigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaArtigos.API.Models.Comentario", "ComentarioPai")
                        .WithMany("Respostas")
                        .HasForeignKey("IdComentarioPai")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SistemaArtigos.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artigo");

                    b.Navigation("ComentarioPai");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaArtigos.API.Models.Favorito", b =>
                {
                    b.HasOne("SistemaArtigos.API.Models.Artigo", "Artigo")
                        .WithMany()
                        .HasForeignKey("IdArtigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaArtigos.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artigo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaArtigos.API.Models.RascunhoDArtigo", b =>
                {
                    b.HasOne("SistemaArtigos.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaArtigos.API.Models.Comentario", b =>
                {
                    b.Navigation("Respostas");
                });
#pragma warning restore 612, 618
        }
    }
}
